#!/bin/sh

script_dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd "$script_dir/.."

echo "// This is generated by \`make secrets\`. Don't edit. \nlet POAP_API_KEY = \"$POAP_API_KEY\"" > ./Packages/ClientPackage/Sources/POAPClient/Secrets.swift
echo "import Foundation\n\nlet baseURL = URL(string: \"https://chaotic-quiet-meme.discover.quiknode.pro/86804d1e5443408f5fe8f2c85d421bf018dbe433\")!" > ./Packages/ClientPackage/Sources/QuickNodeClient/Secrets.swift
echo $FILE_FIREBASE_PRODUCTION | base64 -D > App/iOS/Production/GoogleService-Info.plist
echo $FILE_FIREBASE_PRODUCTION | base64 -D > App/WidgetExtension/Production/GoogleService-Info.plist
