runs:
  using: "Composite"
  steps:
    - name: Cache Swift Packages
      uses: actions/cache@v3
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('caaaption.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-
