// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "POAPPreview",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "POAPPreview",
            targets: ["POAPPreviewModule"],
            bundleIdentifier: "com.caaaption.POAPPreview",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .magicWand),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(name: "caaaption", path: "../../Package"),
    ],
    targets: [
        .executableTarget(
            name: "POAPPreviewModule",
            dependencies: [
                .productItem(
                    name: "POAPWidgetFeature",
                    package: "caaaption"
                ),
            ],
            path: "."
        ),
    ]
)