name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build-caaaption:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: make build-caaaption

  build-previews:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: make build-previews

  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test
