name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo xcode-select -s /Applications/Xcode_14.2.app
    - run: make build-caption

  previews:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo xcode-select -s /Applications/Xcode_14.2.app
    - run: make build-previews