name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    steps:
      - uses: actions/checkout@v3
      - run: make bootstrap
      - run: make build-${{ matrix.env }}

  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - run: make bootstrap
      - run: make test

  approve:
    if: |
      github.event.pull_request.user.login == github.repository_owner && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
