name: CI

on:
  push:
  workflow_dispatch:

env:
  FILE_FIREBASE_STAGING: ${{ secrets.FILE_FIREBASE_STAGING }}
  FILE_FIREBASE_Production: ${{ secrets.FILE_FIREBASE_Production }}

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    steps:
      - uses: actions/checkout@v3
      - run: make bootstrap
      - run: make build-${{ matrix.env }}

  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - run: make bootstrap
      - run: make test
