name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('caaaption.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-
    - run: make build
