name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: make bootstrap
    - run: make build

  test-client-package:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: make bootstrap
    - run: xcodebuild test -workspace caaaption.xcworkspace -sdk iphonesimulator -scheme APIKitTests
