name: CI

on:
  push:
  workflow_dispatch:

env:
  FILE_FIREBASE_STAGING: ${{ secrets.FILE_FIREBASE_STAGING }}
  FILE_FIREBASE_PRODUCTION: ${{ secrets.FILE_FIREBASE_PRODUCTION }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    steps:
      - uses: actions/checkout@v3
      - run: make bootstrap
      - uses: ./.github/actions/spm-cache
      - run: make build-${{ matrix.env }}

  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - run: make bootstrap
      - uses: ./.github/actions/spm-cache
      - run: make test
