name: Format

on:
  push:
    branches:
      - main

jobs:
  format:
    name: swift-format
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - run: make format
      - continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Run swift-format"
          git push