name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  version:
    name: Auto update version
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./.github/workflows/scripts/auto-update-version.sh
      - continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Auto update CFBundleShortVersionString"
          git push
